export const browserCoreExamples = [
  "opsagent browser status",
  "opsagent browser start",
  "opsagent browser stop",
  "opsagent browser tabs",
  "opsagent browser open https://example.com",
  "opsagent browser focus abcd1234",
  "opsagent browser close abcd1234",
  "opsagent browser screenshot",
  "opsagent browser screenshot --full-page",
  "opsagent browser screenshot --ref 12",
  "opsagent browser snapshot",
  "opsagent browser snapshot --format aria --limit 200",
  "opsagent browser snapshot --efficient",
  "opsagent browser snapshot --labels",
];

export const browserActionExamples = [
  "opsagent browser navigate https://example.com",
  "opsagent browser resize 1280 720",
  "opsagent browser click 12 --double",
  'opsagent browser type 23 "hello" --submit',
  "opsagent browser press Enter",
  "opsagent browser hover 44",
  "opsagent browser drag 10 11",
  "opsagent browser select 9 OptionA OptionB",
  "opsagent browser upload /tmp/file.pdf",
  'opsagent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opsagent browser dialog --accept",
  'opsagent browser wait --text "Done"',
  "opsagent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opsagent browser console --level error",
  "opsagent browser pdf",
];
